# Conexão com o banco que você mostrou na foto
spring.datasource.url=jdbc:postgresql://localhost:5432/forum_hub
spring.datasource.username=postgres
spring.datasource.password=495422

# Mantemos o 'update' para o Hibernate criar as tabelas para você
spring.jpa.hibernate.ddl-auto=update

# Configuração para ver o que está acontecendo no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
api.security.token.secret=12345678